web/app_package/dashboard/routes.py
from tokenize import cookie_re
from flask import Blueprint
from flask import render_template, url_for, redirect, flash, request, abort, session,\
    Response, current_app, send_from_directory
# import bcrypt
from wsh_models import sess, Users, login_manager, User_location_day, Oura_sleep_descriptions
from flask_login import login_required, login_user, logout_user, current_user
from datetime import datetime
import numpy as np
import pandas as pd
from app_package.dashboard.utilsChart import make_oura_df, make_user_loc_day_df, \
    make_weather_hist_df, make_chart, buttons_dict_util
import json
import os


dash = Blueprint('dash', __name__)

@dash.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    print('current_User: ', current_user.email)
    page_name = 'Dashboard'

    USER_ID = current_user.id if current_user.id !=2 else 1

    any_loc_hist = sess.query(User_location_day).filter_by(user_id=USER_ID).all()
    any_oura_hist = sess.query(Oura_sleep_descriptions).filter_by(user_id=USER_ID).all()

    corr_dict = False

    # Buttons for dashboard table to toggle on/off correlations
    buttons_dict = {}
    dashboard_routes_dir = os.path.join(os.getcwd(),'app_package', 'dashboard')
    if request.method == 'POST':
        formDict = request.form.to_dict()

        buttons_dict = buttons_dict_util(formDict, dashboard_routes_dir, buttons_dict)

    if os.path.exists(os.path.join(dashboard_routes_dir,'buttons_dict.json')):
        with open(os.path.join(dashboard_routes_dir,'buttons_dict.json')) as json_file:
            buttons_dict = json.load(json_file)

    if len(any_loc_hist) > 0 or len(any_oura_hist) > 0:
        
        print('*** Acceing for Strnagers Data ****')
        df_oura_scores = make_oura_df()
        if df_oura_scores is None:
            df_oura_scores = []

        df_loc_da = make_user_loc_day_df()
        if df_loc_da is None:
            df_loc_da = []

        df_weath_hist = make_weather_hist_df()
        if df_weath_hist is None:
            df_weath_hist = []


        
        # Make weather history for only days the user has locations i.e. match on date and loc_id based on df_loc_day
        df_user_date_temp = pd.merge(df_loc_da, df_weath_hist, 
            how='left', left_on=['date', 'location_id'], right_on=['date', 'location_id'])
        df_user_date_temp = df_user_date_temp[df_user_date_temp['temp'].notna()]

        print('---> THIS NEEDS TO be more than 0:::::: ', len(df_user_date_temp) )
        # print(df_user_date_temp)
        # print(df_oura_scores)



        if len(df_oura_scores) > 0 and len(df_user_date_temp) > 0:
        # if df_oura_scores is not None and df_user_date_temp is not None:
            print('-----> User has both oura and locaiton data')

            #TODO: This needs to concatenate
            df_oura_scores = df_oura_scores.set_index('date')
            df_user_date_temp = df_user_date_temp.set_index('date')

            df = pd.concat([df_user_date_temp, df_oura_scores], axis = 1)
            df.drop('id', inplace = True, axis = 1)
            df = df.where(pd.notnull(df), -99)
            df.reset_index(inplace = True)
            df['cloudcover'] = df['cloudcover'].astype(float)

            temp_data_list = [round(float(temp)) for temp in df['temp'].to_list() ]
            cloudcover_list = [round(float(cloudcover)) for cloudcover in df['cloudcover'].to_list() ]
            sleep_data_list = df['score'].to_list()
            dates_list =[datetime.strptime(i,'%Y-%m-%d') for i in df['date'].to_list() ]

            lists_tuple = (dates_list, sleep_data_list, temp_data_list, cloudcover_list)


            # resize df to remove empty avg temperature calculate correlation:
            df = df[df['temp']!=-99]   
            df = df[df.score != -99]    

            if len(df) > 2:
                print('--- Has enough observations for correlations ----')
                
                corr_dict = {}
                corr_dict['avg_temp'] = round(df['temp'].corr(df['score']),2)
                corr_dict['cloudiness'] = round(df['cloudcover'].corr(df['score']),2)
                # print(df['cloudcover'].to_list())
                # print(df.dtype)
            else:
                print('--- Has DOES NOT enough observations for correlations ----')
                corr_dict = 'too small sample'


        #If user has 
        elif len(df_oura_scores) > 0 and corr_dict==False:
            print('-----> User has only oura data')
        # elif df_oura_scores is not None:
            df_oura_scores = df_oura_scores.drop_duplicates(subset='date', keep='last')
            df = df_oura_scores.copy()
            dates_list =[datetime.strptime(i,'%Y-%m-%d') for i in df['date'].to_list() ]
            sleep_data_list = df['score'].to_list()
            temp_data_list = 'is empty'
            cloudcover_list = 'is empty'
            # lists_tuple = (dates_list, sleep_data_list, temp_data_list)
            
        elif len(df_user_date_temp) > 0 and corr_dict == False:
            print('-----> User has only locaiton data')
        # elif df_user_date_temp is not None:
            df = df_user_date_temp.copy()
            dates_list =[datetime.strptime(i,'%Y-%m-%d') for i in df['date'].to_list() ]
            temp_data_list = [round(float(temp)) for temp in df['temp'].to_list() ]
            cloudcover_list = [round(float(cloudcover)) for cloudcover in df['cloudcover'].to_list() ]
            # cloudcover_list = [cloudcover for cloudcover in df['cloudcover'].to_list() ]
            sleep_data_list = 'is empty'
            
        lists_tuple = (dates_list, sleep_data_list, temp_data_list, cloudcover_list)


        #Use list data to make chart
        script_b, div_b, cdn_js_b = make_chart(lists_tuple, buttons_dict)

        # print(script_b)

        return render_template('dashboard.html', page_name=page_name,
            script_b = script_b, div_b = div_b, cdn_js_b = cdn_js_b, corr_dict=corr_dict, buttons_dict=buttons_dict)
    else:
        df = ''

        return render_template('dashboard_empty.html', page_name=page_name)

web/app_package/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash, request, \
    abort, session, Response, current_app, send_from_directory
import bcrypt
from wsh_models import sess, Users, login_manager, Oura_token, Locations, \
    Weather_history, User_location_day, Oura_sleep_descriptions
from flask_login import login_required, login_user, logout_user, current_user
import requests
#Oura
from app_package.users.utils import oura_sleep_call, oura_sleep_db_add
#Location
from app_package.users.utils import call_location_api, location_exists, \
    add_weather_history, gen_weather_url, add_new_location
#Email
from app_package.users.utils import send_reset_email, send_confirm_email

from sqlalchemy import func
from datetime import datetime, timedelta
import time


salt = bcrypt.gensalt()


users = Blueprint('users', __name__)

@users.route('/', methods=['GET', 'POST'])
def home():
    if current_user.is_authenticated:
        return redirect(url_for('dash.dashboard'))
    if request.method == 'POST':
        formDict = request.form.to_dict()
        if formDict.get('login'):
            return redirect(url_for('users.login'))
        elif formDict.get('register'):
            return redirect(url_for('users.register'))

    return render_template('home.html')

@users.route('/login', methods = ['GET', 'POST'])
def login():
    print('* in login *')
    if current_user.is_authenticated:
        return redirect(url_for('dash.dashboard'))
    page_name = 'Login'
    if request.method == 'POST':
        formDict = request.form.to_dict()
        print('**** formDict ****')
        print(formDict)
        email = formDict.get('email')

        user = sess.query(Users).filter_by(email=email).first()
        print('user for logging in:::', user)
        # verify password using hash
        password = formDict.get('password_text')

        if user:
            if password:
                if bcrypt.checkpw(password.encode(), user.password):
                    print("match")
                    login_user(user)
                    flash('Logged in succesfully', 'info')

                    return redirect(url_for('dash.dashboard'))
                else:
                    flash('Password or email incorrectly entered', 'warning')
            else:
                flash('Must enter password', 'warning')
        elif formDict.get('btn_login_as_guest'):
            print('GUEST EMAIL::: ', current_app.config['GUEST_EMAIL'])
            user = sess.query(Users).filter_by(id=2).first()
            login_user(user)
            flash('Logged in succesfully as Guest', 'info')

            return redirect(url_for('dash.dashboard'))
        else:
            flash('No user by that name', 'warning')

        # if successsful login_something_or_other...


    
    return render_template('login.html', page_name = page_name)

@users.route('/register', methods = ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('dash.dashboard'))
    page_name = 'Register'
    if request.method == 'POST':
        formDict = request.form.to_dict()
        new_email = formDict.get('email')
        check_email = sess.query(Users).filter_by(email = new_email)
        hash_pw = bcrypt.hashpw(formDict.get('password_text').encode(), salt)
        new_user = Users(email = new_email, password = hash_pw)
        sess.add(new_user)
        sess.commit()
        flash(f'Succesfully registerd: {new_email}', 'info')
        return redirect(url_for('users.login'))

    return render_template('register.html', page_name = page_name)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.home'))


@users.route('/account', methods = ['GET', 'POST'])
@login_required
def account():
    page_name = 'Account Page'
    email = current_user.email

    existing_oura_token =sess.query(Oura_token, func.max(
        Oura_token.id)).filter_by(user_id=current_user.id).first()[0]
    
    # other_users_email_list = [i.email for i in sess.query(Users).filter(Users.id != current_user.id).all()]
    # print('*****  Not current user  ***')
    print('Current User: ', current_user.email)
    # print('All other users: ', other_users_email_list)

    user = sess.query(Users).filter_by(id = current_user.id).first()
    

    print('Current user Latitude: ', user.lat)
    if user.lat == None or user.lat == '':
        existing_coordinates = ''
    else:
        existing_coordinates = f'{user.lat}, {user.lon}'
        
    
    if existing_oura_token:
        oura_token = current_user.oura_token_id[-1].token
        existing_oura_token_str = str(existing_oura_token.token)
    else:
        oura_token = ''
        existing_oura_token_str = ''


    if request.method == 'POST':
        if current_user.id == 2:
            flash('Guest can enter any values but they will not change the database', 'info')
            return redirect(url_for('users.account'))
        else:
            startTime_post = time.time()
            formDict = request.form.to_dict()
            new_token = formDict.get('oura_token')
            new_location = formDict.get('location_text')
            email = formDict.get('email')
            user = sess.query(Users).filter_by(id = current_user.id).first()
            yesterday = datetime.today() - timedelta(days=1)
            yesterday_formatted =  yesterday.strftime('%Y-%m-%d')
            user_loc_days = sess.query(User_location_day).filter_by(user_id=current_user.id).all()
            user_loc_days_date_dict = {i.date : i.id for i in user_loc_days}

            #1) User adds Oura_token data
                #a cases oura_token was blank and not it is not
                #b case oura_token was not blank and not it is different than before
            if new_token != existing_oura_token_str:#<-- if new token is different 
                print('------ New token detected ------')
                #1-1a) if user has token replace it
                if existing_oura_token:
                    existing_oura_token.token = new_token
                    sess.commit()
                    oura_token_id = existing_oura_token.id

                #1-1b) else add new token
                else:
                    
                    new_oura_token = Oura_token(user_id = current_user.id,
                        token = new_token)
                    sess.add(new_oura_token)
                    sess.commit()

                    oura_token_id = new_oura_token.id

                #1-1b-1) check if user has oura data yesterday
                oura_yesterday = sess.query(Oura_sleep_descriptions).filter_by(
                    user_id = current_user.id,
                    summary_date = yesterday_formatted).first()
                
                # --> 1-1b-1a) if yes, nothing 


                # --> 1-1b-1b) if no, call API
                if not oura_yesterday:
                    print('---- no data detected yesterday for this user')
                    print('oura_yesterday::')
                    print(oura_yesterday)
                    url_sleep=current_app.config['OURA_API_URL_BASE']#TODO: put this address in config
                    response_sleep = requests.get(url_sleep, headers={"Authorization": "Bearer " + new_token})
                    if response_sleep.status_code ==200:
                        sleep_dict = response_sleep.json()

                # --> 1-1b-2)Response data add to OUra_sleep_desciprtions for each session in response
                        user_sleep_sessions = sess.query(Oura_sleep_descriptions).filter_by(user_id = current_user.id).all()
                        user_sleep_end_list = [i.bedtime_end for i in user_sleep_sessions]
                # -------> 1-1b-2a) if endsleep exists, skip
                
                # -------> 1-1b-2b) if  endsleep NOT exists, add row
                        sessions_added = 0
                        for session in sleep_dict.get('sleep'):
                            if session.get('bedtime_end') not in user_sleep_end_list:

                                for element in list(session.keys()):
                                    if element not in Oura_sleep_descriptions.__table__.columns.keys():
                                        del session[element]

                                #CHECKED check this reference of new_oura_token works????? 
                                #CHECKED 9/16/2022 and it seems to be working fine here
                                session['token_id'] = oura_token_id
                                session['user_id'] = current_user.id

                                # new_oura_session_date = session['summary_date']
                                # new_oura_session_score = session['score']
                                
                                try:
                                    new_oura_session = Oura_sleep_descriptions(**session)
                                    sess.add(new_oura_session)
                                    sess.commit()
                                    # oura_add_successfully = True
                                    sessions_added +=1
                                    
                                except:
                                    print(f"Failed to add oura data row for sleepend: {session.get('bedtime_end')}")
                                    # oura_add_successfully = False
                        flash(f'Successfully added {sessions_added} sleep sesions and updated user Oura Token', 'info')
                    else:
                        print("response_sleep.status_code::", response_sleep.status_code)
                        print('did not add oura data for user becuause token is not accpeted by OUra')
                        flash('Unable to get data from Oura API becuase does not recognize this token', 'warning')
                else:
                    print('-- date detected yesterday for this user')

web/app_package/templates/_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{{ url_for('static', filename='../static/css/main.css') }}">
        
    <!-- Import the Bootstrap stylesheet -->
    <script src="../static/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="../static/node_modules/jquery/dist/jquery.js"></script>


    <title>whatsticks</title>
</head>
<body>
    <section class="navbar_section">







    <div class="navbar navbar_custom  bg-primary " id="nav_section">
    
        <div class="left_and_middle">
            <div class="nav_left">
                <a href="{{ url_for('users.home') }}" >
                    <div class="logo">
                      <img class="dandd_logo" src="../static/images/wshLogo300px.png" >
                    </div>
                </a>
            </div>
           
    
            <div class="middle_nav_div">
                <h1>What Sticks</h1>
                {% if current_user.is_authenticated %}
                <h3>{{ current_user.email }}</h3>
                {% endif %}
            </div>
        </div>

        <img class="mobile-menu" id="mobile-cta" src="../static/images/white-hamburger-menu-icon-24.png" alt="Open Navigation">

        <nav>
            <img id="mobile-exit" class="mobile-menu-exit" src="../static/images/exit.svg" alt="Close Navigation">
            <ul class="primary-nav ul_primary" id="nav_horizontal_list">
                {% if current_user.is_authenticated %}

                <li class="nav-item dropdown li_primary">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown2"role="button"
                        data-bs-toggle="dropdown"aria-expanded="false">About</a>

                    <div class="dropdown-menu wsh_items_alignment" aria-labelledby="navbarDropdown2">
                        <a class="dropdown-item" href="{{ url_for('users.about_us') }}">About</a>
                        <a class="dropdown-item" href="{{ url_for('users.privacy') }}">Privacy</a>
                        

                    </div>
                </li>
                <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('dash.dashboard') }}">Dashboard</a></li>
                <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('users.account') }}">Account</a></li>
                <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
                <!-- <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('users.youtube_request') }}">YouTube Request</a></li> -->
                {% else %}

                <li class="nav-item dropdown li_primary">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown2"role="button"
                        data-bs-toggle="dropdown"aria-expanded="false">About</a>

                    <div class="dropdown-menu wsh_items_alignment" aria-labelledby="navbarDropdown2">
                        <a class="dropdown-item" href="{{ url_for('users.about_us') }}">About</a>
                        <a class="dropdown-item" href="{{ url_for('users.privacy') }}">Privacy</a>
                        

                    </div>
                </li>

                <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('users.login') }}">Login</a></li>
                <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('users.home') }}">Home</a></li>
                <!-- <li class="nav-item li_primary"><a class="nav-link" href="{{ url_for('users.youtube_request') }}">YouTube Request</a></li> -->
                
                
                
                
                {% endif %}
            </ul>
        </nav>

    </section>
    
    <div class = "flash_custom_parent" >
        
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
      
            <div class="alert alert-{{ category }} alert_custom" id="div_flash"  >
              <i class="close icon"></i>
      
              {{ message }}
              <div class="close_right">
                <input type="button" value=&#10006 onclick="removeFlash()" class="btn btn-secondary btn_custom02">
              </div>
              
            </div>
          {% endfor %}
        {% endif %}
        {% endwith %}
      
      </div>

    {% block main %}{% endblock %}

<script>
    const mobileBtn = document.getElementById('mobile-cta')
        nav = document.querySelector('nav')
        mobileBtnExit = document.getElementById('mobile-exit');

    mobileBtn.addEventListener('click', () => {
        nav.classList.add('menu-btn');
    })

    mobileBtnExit.addEventListener('click', () => {
        nav.classList.remove('menu-btn');
    })
</script>

<!-- Remove flash on click -->
<script>
    function removeFlash() {
        const element = document.getElementById('div_flash');
        element.remove();
    }
</script>

<!-- assign navbar height to --nav-height -->
<script>document.documentElement.style.setProperty('--nav-height', `${document.getElementById("nav_section").offsetHeight}px`);</script>

</body>
</html>

web/app_package/templates/about_us.html
{% extends "_layout.html" %}
{% block main %}
<section class="about_us">

  <div class = "about_us_body">
    <div class = "title">
      {{ page_name }}
    </div>

    <div class="div_writing">
        <div class = writing_content>
            Hi I am Nick! Born in Washington DC currently residing in France.  I am the creator of What Sticks. I started building this application because I have a passion for improving our health and wellness. Currently, What Sticks connects with your Oura Ring to trace your sleep score and tracks the weather in your location to give you some sense of how temperature in your location impacts your sleep.
            <br><br>
    
            There is a lot of our data being used being used to advertise to us, but what if we used that data help improve our overall health? What Sticks is right now small step in that future but it’s a step.
            <br><br>
    
            As an economist for 15 years, I started to see the immense power that large datasets could have. For most of my training I was leaning on models with small datasets that tried to be very precise. But as technology has improved and datasets have gotten larger, I’ve found myself more convinced by simpler models that use large datasets. 
            <br><br>
            
            Even though there might be more variables that we need to account for, as a lay person if we find a trend that follows a consistent pattern that might move the needle in my life I would want to be aware and make a decision on it.
            <br><br>
            Amongst many things that have inspired this goal was  an <a href="https://www.pushkin.fm/podcasts/revisionist-history/burden-of-proof">episode of Revisionists History</a>, Malcom Gladwell examines the question of How much more proof do we need? He asks this question and uses the brain disease chronic traumatic encephalopathy (CTE) that has been linked to American Football players. The scientific community has not come to a consensus, but it seems the evidence is overwhelming.
            <br><br>
            I am not in the scientific community and do not aim to give medical advice I just want to use technology that already exists to use.
            <br><br>
            I believe in the future we will have more stronger evidence as technology improves. But I don’t want to shy away from trying to pull together as much data as we have today, which we have a lot, to try to direct our attention to behaviors that are likely to move the needle and align to the lives we want.
            
        </div>

    </div>
    <br>
    <div class="div_writing">
        <h1>More about What Sticks</h1>

        <br>
        <div class="writing_content">
            Article: <a href="https://nrodrig1.medium.com/healthcare-is-not-up-to-date-2e58c01c1477">Healthcare is Not Up To Date</a>
            <br><br>
            iOS device application coming soon!
            <br><br>
            Here are the current Github repos:
            <a href="https://github.com/costa-rica/whatSticks06">Web</a>,
            <a href="https://github.com/costa-rica/whatSticks06api">API</a>,
            <a href="https://github.com/costa-rica/whatSticks06scheduler">Scheduler</a>,
            <a href="https://github.com/costa-rica/whatSticksKivy09">iOS applicaiton</a>
        </div>

    </div>
    <br>
    <div class="div_writing">
        <h1>More about Nick</h1>
        <br>
        <div class="writing_content">
            
            Medium: <a href="https://medium.com/@nrodrig1">Nick Rodriguez</a>
            <br>
            Twitter: <a href="https://twitter.com/EvryMnRodriguez">@EvryMnRodriguez</a>
            <br>
            Github: <a href="https://github.com/costa-rica">costa-rica</a>
            <br>
            LinkedIn: <a href="https://www.linkedin.com/in/nick-rodriguez-0a31a133/">Nick Rodriguez</a>
            <br>
            Email: nick@dashanddata.com
        </div>


    </div>

  </div>

</section>



{% endblock %}

web/app_package/templates/account.html
{% extends "_layout.html" %}
{% block main %}

<section class="account">

    <div class="account_body">
        <div class="title">
            Account page
        </div>

        <div class="register_form">
            <form method="POST" action="">

                <label for="email">Email:</label>
                <input type="text" id="email" name="email" class="register_text" value="{{ email }}"><br><br>


                <!-- <label for="oura_token">Oura Ring Token:</label> -->
                <button type="button" class="btn_to_label" data-bs-toggle="modal" 
                    data-bs-target="#activityModal"><u>Oura Ring Token: </u>
                </button>
                <input type="text" id="oura_token" name="oura_token" class="register_text"
                    value="{{ oura_token }}"><br><br>



                <label for="location_text">Location:</label>
                <input type="text" id="location_text" name="location_text" class="register_text"
                    placeholder="Latitude, Longitude" value = "{{ location_coords }}">

                <div class="element_right">

                    <input class="btn btn-secondary btn_loc" type="button" value=""
                        onclick="getLocation()">
                    <label class="form-check-label password_checkbox">
                        Get Location
                    </label>
    
                </div><br><br>

                <div class="element_right">

                    <input type="submit" value="Update" class="btn btn-secondary btn_custom01">

                </div>

            </form>

        </div>

    </div>

</section>



<div class="modal fade" id="activityModal" tabindex="-1" aria-labelledby="activityModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Get your Oura Ring token</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
            <ol>
                <li>Create an Oura account using the Oura iOS or Android application. Use the same account to sign-in to <a href="https://cloud.ouraring.com">https://cloud.ouraring.com</a>. </li>
                <li>Next enter a reason and copy the token <a href="https://cloud.ouraring.com/personal-access-token ">https://cloud.ouraring.com/personal-access-token </a></li>
            </ol>

            
        </div>
        <!-- <div class="modal-footer">
          <button type="button" class="btn btn-primary">Save changes</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div> -->
      </div>
    </div>
  </div>
  
  

<!-- Get location -->
<script>
    var x = document.getElementById("location_text");

    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
        }
    }

    function showPosition(position) {
        x.value = position.coords.latitude + ", " + position.coords.longitude;
    }
</script>
<!-- location source: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation -->



{% endblock %}

web/app_package/templates/dashboard.html
{% extends "_layout.html" %}
{% block main %}

<section class="dashboard">
    <div class = "title">
        {{ page_name }}
      </div>
    <div class="table_and_chart">

        <div class="table_div_outer">

            <div class="table_flex">
                <form method="POST">
                <div class="table_div">
                    <div class="header header_var">
                        Sleep Score
                    </div>
                
                    <div class="header header_corr">
                        Correlation
                    </div>
                
                
                    <div class="row_header">
                        {% if buttons_dict['avg_temp']!=1 %}
                        <button type="submit" name="avg_temp" value="1" class="btn btn-primary btn_header">Avg Daily Temperature</button>
                        {% else %}
                        <button type="submit" name="avg_temp" value="1" class="btn btn-outline-primary btn_header">Avg Daily Temperature</button>
                        {% endif %}
                    </div>
                    <div class="row_value">
                        {% if buttons_dict['avg_temp']!=1 %}
                        {{ corr_dict['avg_temp'] }}
                      {% else %}
                        Off
                      {% endif %}
                    </div>
                    <div class="row_header">
                        {% if buttons_dict['cloudiness']!=1 %}
                        <button type="submit" value="1" name="cloudiness" class="btn btn-primary btn_header">Cloud Cover</button>
                        {% else %}
                        <button type="submit" value="1" name="cloudiness" class="btn btn-outline-primary btn_header " >Cloud Cover</button>
                        {% endif %}
                    </div>
                    <div class="row_value">
                    {% if buttons_dict['cloudiness']!=1 %}
                        {{ corr_dict['cloudiness'] }}
                    {% else %}
                        Off
                    {% endif %}
                    </div>
                </div>
            </form>
            </div>


        </div>
    
        <div class="bokeh_div">
            {{ div_b|safe }}
        </div>

    </div>



</section>
{{ script_b|safe }}


<script src="../static/bokeh/bokeh-2.4.3.min.js" crossorigin="anonymous"></script>
<script type="text/javascript">
    Bokeh.set_log_level("info");
</script>

{% endblock %}